version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_CONNECTION_STR=mongodb://127.0.0.1:27017/CozaStoreUser
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
